### ISSUE TITLE
We want to vote on positives

### ISSUE THREAD

**Issue by jaller94** [severest/retrobot#248]
Instead of just voting for deltas we also want to be able to vote on the positives.

Mentioned in the Performance Management Team retro today.

**Comment by severest** [comment]
Would the votes be limited to a certain number like the Deltas? Or be more of a 'like' feature. 

What would be the ultimate result of the votes on pluses? Would you expect them to appear on the summary page?

**Comment by jaller94** [comment]
This has not been mentioned again after the meeting.
I assume we don’t want this anymore.
